### ISSUE TITLE
Is there an easy way to do a swipe to dismiss like the twitter app?

### ISSUE THREAD

**Issue by mark8044** [thesmythgroup/easy_image_viewer#14]
As the title says, is there a good way to allow us to swipe the image up or down (but not diagonally) to dismiss the image?

**Comment by jfahrenkrug** [comment]
Hi @mark8044. Great question. I started the work on this in this commit: https://github.com/thesmythgroup/easy_image_viewer/commit/65dbce7432b8745e4077c9bab22d6a0b2fea9057 It uses the `Dismissible` widget. It works well when the user hasn't zoomed in, but I still need to solve the issue of disabling dismissal when the user has zoomed in and wants to pan instead of dismiss.

**Comment by jfahrenkrug** [comment]
I got stuck on a problem with the PageView/PageController. I filed an issue here: https://github.com/flutter/flutter/issues/106708 and asked a question here: https://stackoverflow.com/questions/72779464/flutter-pageview-seems-to-ignore-pagecontrollers-page-property-after-setstate I hope it can be solved.

**Comment by jfahrenkrug** [comment]
@mark8044 I've filed another issue here: https://github.com/flutter/flutter/issues/108961

**Comment by jfahrenkrug** [comment]
Found a solution: https://github.com/thesmythgroup/easy_image_viewer/pull/21
Some background: https://github.com/flutter/flutter/issues/108961#issuecomment-1205147526
