### ISSUE TITLE
Swipe to dismiss is not reponsive or reactive after zoom

### ISSUE THREAD

**Issue by mark8044** [thesmythgroup/easy_image_viewer#57]
If you zoom in to a picture and then zoom out of a picture, then immediately go to try to swipe to dismiss the photo, nothing happens.  If you try to swipe to dismiss a second time then it works properly

It seems the first try to swipe to dismiss is not responsive; perhaps it is being interpreted as a pan motion rather then a swipe to dismiss motion?

**Comment by jfahrenkrug** [comment]
@mark8044 Thanks for reporting. Is this on iOS, Android or both? Thanks!

**Comment by jfahrenkrug** [comment]
I'm closing this since I could not repro this on either iOS or Android. Maybe you hadn't zoomed out all the way before trying to swipe to dismiss? Feel free to reopen if you get around to providing more information and repro steps. Thanks!


https://github.com/thesmythgroup/easy_image_viewer/assets/16358/e455da9b-3a1d-4229-97e1-47e8de80a77e


https://github.com/thesmythgroup/easy_image_viewer/assets/16358/c42db148-eb5a-463e-89da-cd5195ff2c9c
