### ISSUE TITLE
Any plans to add support for flutter_svg?

### ISSUE THREAD

**Issue by yamashita-room-335** [thesmythgroup/easy_image_viewer#69]
## Describe the Feature

Any plans to add support for flutter_svg?
https://pub.dev/packages/flutter_svg

I think there are some people who want to.

Also, similar support requests include rive, and lottie.
https://pub.dev/packages/rive
https://pub.dev/packages/lottie

**Comment by jfahrenkrug** [comment]
Hi @kouroku-room,

Thank you for your question. There are currently no plans to add built-in support for specific third party libraries. However, it is already possible to render custom views with EasyImageViewer (not just images).

From the README:

>> You can subclass EasyImageProvider [...] Finally, you can even override the imageWidgetBuilder method and completely customize the appearance of each individual image. Keep in mind that it should be an "image-like" widget since it will be treated as such: the user can pinch&zoom the returned widget etc.

You can see the default implementation here: https://github.com/thesmythgroup/easy_image_viewer/blob/bb64f705ac92800209c9eeb0ec488fb70001f21d/lib/src/easy_image_provider.dart#L21
Instead of returning an `Image` widget, you can return any widget you'd like (as long as it is "image-like"). 

Here's an example of how to use your own subclass of `EasyImageProvider`:
https://github.com/thesmythgroup/easy_image_viewer/blob/bb64f705ac92800209c9eeb0ec488fb70001f21d/example/lib/main.dart#L231
and
https://github.com/thesmythgroup/easy_image_viewer/blob/bb64f705ac92800209c9eeb0ec488fb70001f21d/example/lib/main.dart#L137

Equipped with those tools, you should be able to any kind of custom widget you'd like, including SVGs etc.
